# Timeline Theme Configuration

# Theme settings
theme_name: "timeline"
version: "1.0.0"

# Layout settings
layout:
  archive_per_page: 10
  category_per_page: 10
  tag_per_page: 10

# Color scheme (black and white theme)
colors:
  primary: "#000000"
  secondary: "#ffffff" 
  accent: "#333333"
  text: "#1a1a1a"
  text_light: "#666666"
  background: "#ffffff"
  card_bg: "#fafafa"
  border: "#e0e0e0"

# Typography
typography:
  font_family: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"
  font_size: "16px"
  line_height: "1.6"

# Timeline settings
timeline:
  enable_animation: true
  animation_duration: "0.3s"
  scroll_animation: true
  
# Performance
performance:
  lazy_load: true
  minify_css: true
  minify_js: true

# Social sharing
social:
  enable: false

# Comments
comments:
  enable: false